// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CasoAgregarCliente</b><br>
 * Generated     : <b>2016/11/26 20:49:08</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 8 amd64 6.2 <br>
 * 
 * @since  noviembre 26, 2016
 * @author Adriana
 */
public abstract class CasoAgregarClienteHelper extends RationalTestScript
{
	/**
	 * Aceptar: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Aceptar
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject aceptar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("aceptar"));
	}
	/**
	 * Aceptar: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Aceptar
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject aceptar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("aceptar"), anchor, flags);
	}
	
	/**
	 * Aceptar: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Aceptar
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject aceptar2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("aceptar2"));
	}
	/**
	 * Aceptar: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Aceptar
	 * 		name : OptionPane.button
	 * 		.classIndex : 0
	 */
	protected GuiTestObject aceptar2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("aceptar2"), anchor, flags);
	}
	
	/**
	 * Agregar: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Agregar
	 * 		iconDescription : add-user.png
	 * 		.classIndex : 0
	 */
	protected GuiTestObject agregar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("agregar"));
	}
	/**
	 * Agregar: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Agregar
	 * 		iconDescription : add-user.png
	 * 		.classIndex : 0
	 */
	protected GuiTestObject agregar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("agregar"), anchor, flags);
	}
	
	/**
	 * Cliente: with default state.
	 *		.captionText : Cliente
	 * 		.class : Clte
	 * 		accessibleContext.accessibleName : Cliente
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject cliente() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("cliente"));
	}
	/**
	 * Cliente: with specific test context and state.
	 *		.captionText : Cliente
	 * 		.class : Clte
	 * 		accessibleContext.accessibleName : Cliente
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject cliente(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("cliente"), anchor, flags);
	}
	
	/**
	 * Clientes: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Clientes
	 * 		iconDescription : usuarioo.png
	 * 		.classIndex : 4
	 */
	protected GuiTestObject clientes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("clientes"));
	}
	/**
	 * Clientes: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Clientes
	 * 		iconDescription : usuarioo.png
	 * 		.classIndex : 4
	 */
	protected GuiTestObject clientes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("clientes"), anchor, flags);
	}
	
	/**
	 * Contraseña: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Contraseña:  
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject contraseña() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("contraseña"));
	}
	/**
	 * Contraseña: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Contraseña:  
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject contraseña(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("contraseña"), anchor, flags);
	}
	
	/**
	 * Empleado: with default state.
	 *		label : Empleado
	 * 		.class : java.awt.Checkbox
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject empleado() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("empleado"));
	}
	/**
	 * Empleado: with specific test context and state.
	 *		label : Empleado
	 * 		.class : java.awt.Checkbox
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject empleado(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("empleado"), anchor, flags);
	}
	
	/**
	 * Entrar: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Entrar
	 * 		iconDescription : users.png
	 * 		.classIndex : 2
	 */
	protected GuiTestObject entrar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("entrar"));
	}
	/**
	 * Entrar: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Entrar
	 * 		iconDescription : users.png
	 * 		.classIndex : 2
	 */
	protected GuiTestObject entrar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("entrar"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject jTextField() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject jTextField(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 1
	 */
	protected TextGuiSubitemTestObject jTextField2() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField2"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 1
	 */
	protected TextGuiSubitemTestObject jTextField2(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField2"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 2
	 */
	protected TextGuiSubitemTestObject jTextField3() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField3"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 2
	 */
	protected TextGuiSubitemTestObject jTextField3(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField3"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 4
	 */
	protected TextGuiSubitemTestObject jTextField4() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField4"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 4
	 */
	protected TextGuiSubitemTestObject jTextField4(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField4"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 3
	 */
	protected TextGuiSubitemTestObject jTextField5() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField5"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 3
	 */
	protected TextGuiSubitemTestObject jTextField5(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField5"), anchor, flags);
	}
	
	/**
	 * Login: with default state.
	 *		.captionText : Login
	 * 		.class : Login
	 * 		accessibleContext.accessibleName : Login
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject login() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("login"));
	}
	/**
	 * Login: with specific test context and state.
	 *		.captionText : Login
	 * 		.class : Login
	 * 		accessibleContext.accessibleName : Login
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject login(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("login"), anchor, flags);
	}
	
	/**
	 * Mostrar: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Mostrar
	 * 		iconDescription : open-sign.png
	 * 		.classIndex : 2
	 */
	protected GuiTestObject mostrar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("mostrar"));
	}
	/**
	 * Mostrar: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Mostrar
	 * 		iconDescription : open-sign.png
	 * 		.classIndex : 2
	 */
	protected GuiTestObject mostrar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("mostrar"), anchor, flags);
	}
	
	

	protected CasoAgregarClienteHelper()
	{
		setScriptName("CasoAgregarCliente");
	}
	
}

